<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris_load = load_iris()
iris = pd.DataFrame(iris_load.data, columns=iris_load.feature_names)
iris['Class'] = iris_load.target

# 숫자 레이블을 문자열 범주로 변환
iris['Class'] = iris['Class'].map({
    0: 'Setosa',
    1: 'Versicolor',
    2: 'Virginica'
})

# 여기서는 나중에 사용하기 위해 iris 사본을 저장해 둡니다.
iris_origin = iris.copy()

In [2]:
class_group = {
    'Setosa': 'Group_A',
    'Versicolor': 'Group_B',
    'Virginica': 'Group_B'
}

iris['Class_group'] = iris['Class'].map(class_group)

iris[['Class', 'Class_group']].head()

    Class Class_group
0  Setosa     Group_A
1  Setosa     Group_A
2  Setosa     Group_A
3  Setosa     Group_A
4  Setosa     Group_A

In [3]:
iris['Class_label2'] = pd.factorize(iris['Class'])[0]
iris[['Class', 'Class_label2']].head()

    Class  Class_label2
0  Setosa             0
1  Setosa             0
2  Setosa             0
3  Setosa             0
4  Setosa             0

In [4]:
iris['petal_length_group'] = pd.cut(
    iris['petal length (cm)'],
    bins=[0, 2, 5, 10],
    labels=['Short', 'Medium', 'Long']
)

iris[['petal length (cm)', 'petal_length_group']].head()

   petal length (cm) petal_length_group
0                1.4              Short
1                1.4              Short
2                1.3              Short
3                1.5              Short
4                1.4              Short

In [5]:
iris_dummy = pd.get_dummies(iris_origin, columns = ['Class'])
iris_dummy.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Class_Setosa,Class_Versicolor,Class_Virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0

In [6]:
iris_onehot = pd.get_dummies(
    iris_origin, columns=['Class'], drop_first=True
)
iris_onehot.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Class_Versicolor,Class_Virginica
0,5.1,3.5,1.4,0.2,0,0
1,4.9,3.0,1.4,0.2,0,0
2,4.7,3.2,1.3,0.2,0,0
3,4.6,3.1,1.5,0.2,0,0
4,5.0,3.6,1.4,0.2,0,0